version: '3'

services:
  postgres:
    image: "postgres:9-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: your_kid_sucks
    expose:
      - 5432
    ports:
      - "5432:5432"
